{{ $realmSecretName := printf "%s-realm" .Values.keycloak.name }}
apiVersion: v1
kind: keycloak-cert-configmap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap1 # ms-azure-postgres-cert
data:
  file-postgres-cert: |
  -----BEGIN CERTIFICATE-----
    MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
    QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
    b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
    CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
    nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
    43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
    T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
    gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
    BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
    TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
    DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
    hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
    06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
    PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
    YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
    CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
    -----END CERTIFICATE-----
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    {{- include "h.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.keycloak.name }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "h.labels" . | nindent 8 }}
        app: {{ .Values.keycloak.name }}
      annotations:
        checksum/{{ .Values.databases.keycloak_db.name }}: {{ toJson .Values.databases.keycloak_db | sha256sum }}
        checksum/realm: {{ .Files.Get "resources/oasis-realm.json" | sha256sum }}
    spec:
      {{- include "h.affinity" . | nindent 6 }}
      initContainers:
        {{- include "h.initTcpAvailabilityCheckBySecret" (list . .Values.databases.keycloak_db.name) | nindent 8}}
      containers:
        - name: {{ .Values.keycloak.name }}
          image: {{ .Values.images.keycloak.image }}:{{ .Values.images.keycloak.version }}
          args: ["start", "--import-realm"]
          ports:
            - containers: {{ .Values.keycloak.port }}
          env:
            - name: KC_DB_URL_PROPERTIES
              value: "?sslmode=verify-full&sslcert=root.crt"
            - name: KC_LOGLEVEL
              value: DEBUG
            - name: PROXY_ADDRESS_FORWARDING            
          volumeMounts:
            - name: keycloak-cert
              mountPath: /opt/keycloak/.postgresql/root.crt
              subPath: file-postgres-cert
      volumes: 
        - name: keycloak-cert
          configMap:
            name: {{ .Values.keycloak.certConfigMapName }}
        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    {{- include "h.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}
      protocol: TCP
      name: keycloak-http
  selector:
    {{- include "h.selectorLabels" . | nindent 4 }}
    app: {{ .Values.keycloak.name }}