images:
  redis:
    image: valkey/valkey
    version: 8.1.1-alpine3.21

databases:
  channel_layer:
    type: redis
    name: valkey
    port: 6379
    ssl: false

azure:
  secretProvider:
    secrets:
      channel-layer:
        - key: password
          objectName: valkey-auth
