apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
data:
  db-init.sh: |-
    {{- .Files.Get "resources/db-init.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  labels:
    oasislmf/type: azure-db-init
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: db-init
          image: {{ .Values.images.image }}:{{- .Values.images.version }}
          env:
            - name: OASIS_DB_SERVER_NAME
              valueFrom:
                secretKeyRef:
                  name: oasis-db-server-name
                  key: oasis-db-server-name
            - name: OASIS_DB_SERVER_HOST
              value: mydemoserver-pg-oasis.postgres.database.azure.com
            - name: OASIS_DB_SERVER_ADMIN_USERNAME
              value: oasisadmin
            - name: PGPASSWORD
              value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtXYmthYTZxczh3c1RuQndpaU5ZT2hIYm5BdyIsImtpZCI6ImtXYmthYTZxczh3c1RuQndpaU5ZT2hIYm5BdyJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxMmViMTJmLWM5OTUtNDVlZi1iZmVhLWVhYzdhZWNhMDc1NS8iLCJpYXQiOjE3MDczMjA4NzQsIm5iZiI6MTcwNzMyMDg3NCwiZXhwIjoxNzA3MzI2MTQ0LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFZBQUFBWVV3ZEVCdmdXWXJBQy9NWnA5S3BHckpBbEdmdkl1cUZIRGRSUk1USTU5N202eWFmR1BrcXlodjlmdE1tbkpjRnRTUVVzbEtBZVkrOWR0RXg5cHBZR2l6ZzFnRVliUVVnMjZ1VXpqL3NFaTQ9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6ImI2NzdjMjkwLWNmNGItNGE4ZS1hNjBlLTkxYmE2NTBhNGFiZSIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiRWZmYWgiLCJnaXZlbl9uYW1lIjoiUm9kbmV5IiwiaXBhZGRyIjoiMmEwMjpjN2M6YWUyODozYTAwOjQyMGE6Y2M4ZjplY2VlOmI4NTMiLCJuYW1lIjoiUm9kbmV5IEVmZmFoIiwib2lkIjoiMjlhYTU3ZjktY2YxOS00Y2U1LTg4NzYtOTFlZDNhNTRlNTEzIiwicHVpZCI6IjEwMDMyMDAzMDY2MThGNTciLCJyaCI6IjAuQVU4QUw3RXVnWlhKNzBXXzZ1ckhyc29IVlZEWVBCTGYyYjFBbE5YSjhIdF9vZ05QQUxrLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IlNFSUhQRHZwa0hxVlJNRFo1ZXVuX1NsRGJrUlo3NUR6cUlQcWlGdUdCRU0iLCJ0aWQiOiI4MTJlYjEyZi1jOTk1LTQ1ZWYtYmZlYS1lYWM3YWVjYTA3NTUiLCJ1bmlxdWVfbmFtZSI6InJvZG5leUBvYXNpc2xtZmVudGVycHJpc2Uub25taWNyb3NvZnQuY29tIiwidXBuIjoicm9kbmV5QG9hc2lzbG1mZW50ZXJwcmlzZS5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJZVWFXZXFZbngwLTQ0aVlVSHZ5MUFRIiwidmVyIjoiMS4wIn0.lfCSL4kPuzN5Ks1MeOEKknpND28vpdvim5lfpGpEs8WZYySW00Fm6oNQ4id3V3Yfz3ijXv9pJou9Y86E0ALlNFsA3qsDIM69XDJIDHJRbjlbCEti99TEuHM5jx0qXsyhKn2Qo7ULVnnNDlJ2UwUYVYyU3HSDrpJ6MtTwcEZdDskNPPsvfUNfVLmnxTKLyi6-QKM8OBI0v0JVN17b4UqJlEpK6oRGXbNXD44VO8jK3mbmztqJPsheoY8ccTRiP4kf5gwQHMXps5sL6SE5uwkUms831L2g3vmGQjZqzDO5zI1qZfTNJTTS77FPYe5D6ZtywnQqR8oZcvR5CABvG-pA5Q"
            - name: OASIS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oasis-db-username
                  key: oasis-db-username
            - name: OASIS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oasis-db-password
                  key: oasis-db-password
            - name: KEYCLOAK_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-username
                  key: keycloak-db-username
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-password
                  key: keycloak-db-password
            - name: CELERY_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: celery-db-username
                  key: celery-db-username
            - name: CELERY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: celery-db-password
                  key: celery-db-password
          volumeMounts:
            - name: db-init-script
              mountPath: /tmp/db-init.sh
              subPath: db-init.sh
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          command: ["sh", "-c", "/tmp/db-init.sh"]
      volumes:
        - name: db-init-script
          configMap:
            name: db-init-scripts
            defaultMode: 0777
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-db-init-secret-provider"
      restartPolicy: Never
  backoffLimit: 4
